default:
    git: true
    git_version: master
    git_repo: {{config_dir}}/..
    template: {{config_dir}}/templates/changelog.tpl.rst
    exe:
        version: python setup.py --version | tr -d '\n'
