default:
  redmine_user: jsl
  redmine_project: duataric
  redmine_url: http://redmine

  hg_repo: ssh://hg@repositorios/tariczilla
  hg_version: '3.5.13'

  data:
    project: duasql

profiles:
  email:
    redmine: true
    redmine_project: tariczilla
    template: {{config_dir}}/email.tpl.md

  changelog:
    template: {{config_dir}}/changelog.tpl.rst
    redmine: true
    data:
      trackers:
        errores: error
        tareas: feature

  hg:
    template: {{config_dir}}/hg.tpl.txt
    hg: true
  chef:
    template: {{config_dir}}/chef.tpl.txt
    chef: true
  apt:
    template: {{config_dir}}/apt.tpl.txt
    apt: true
    apt_url: http://apt
    apt_packages:
      - tnote
      - caronte
